baseURL = "https://gabientt.github.io/"
languageCode = "pt-br"
title = "Enquanto Compila | Gabriely Vicente"
theme = "PaperMod"

[params]
  description = "Projetos e anotações de um engenheiro de computação"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
